version: '3.7'
services:
  db:
    container_name: postgres_lah
    build:
      context: ./db
    ports:
    - "5432:5432"
  credit_history:
    container_name: credit_history_lah
    build:
      context: ./credit-history/credit-history-server
    ports:
    - "8000:8080"
    command: java -jar credit-history.jar
  loan:
    container_name: loan_lah
    build:
      context: ./loan/loan-server
    ports:
    - "8010:8080"
    command: java -jar loan.jar