version: '3.7'
services:
  db:
    container_name: postgres_lah
    build:
      context: ./db
    ports:
    - "5432:5432"
  credit_history:
    container_name: credit_history_lah
    build:
      context: ./credit-history/credit-history-server
    ports:
    - "8000:8080"
    command: java -jar credit-history.jar
  loan:
    container_name: loan_lah
    build:
      context: ./loan/loan-server
    ports:
    - "8010:8080"
    command: java -jar loan.jar
  app_db:
    container_name: app_db_lah
    build:
      context: ./db
    ports:
    - "6543:5432"
  app:
    container_name: app_lah
    build:
      context: ./loans-lah-app
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=loans
      - DB_USER=loan
      - DB_PASSWORD=secret
      - DB_HOST=app_db_lah
      - JWT_SECRET=superSecret
    depends_on:
      - app_db
