version: '3.7'
services:
  loan_db:
    container_name: laon-db-lah
    build:
      context: ../db
    ports:
    - "5432:5432"
  loan:
    container_name: loan-lah
    build:
      context: ../loan/loan-server
    ports:
    - "8010:8080"
    command: java -jar loan.jar
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://laon-db-lah:5432/loans
  app_db:
    container_name: app-db-lah
    build:
      context: ../db
    ports:
    - "6543:5432"
  app:
    container_name: app-lah
    build:
      context: ../loans-lah-app
    ports:
    - "8910:3000"
    environment:
    - DB_NAME=loans
    - DB_USER=loan
    - DB_PASSWORD=secret
    - DB_HOST=app-db-lah
    - JWT_SECRET=superSecret
    - LOAN_SERVER=http://loan-lah:8080
    depends_on:
    - app_db
