spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loans
    username: loan
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    enabled: true

# https://hibernate.atlassian.net/browse/HHH-12368
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR